### PR TITLE
Update practice-exam-8.md

### PR DESCRIPTION
**Pull request by Nivedithabp**
Fixing the answers for Question 28
AWS Marketplace does offer selling your / 3rd party software solutions

### CODE REVIEW

**Comment by rebeus** [comment]
Please raise this as an issue @Nivedithabp

**Review by mvssales — APPROVED** [review]

**Review by Senam-Kudjo — COMMENTED** [review]
Its wrong because AWS Marketplace primarily provides software solutions that are designed to run on AWS, not necessarily on other cloud vendors.

**Comment by Senam-Kudjo** [comment]
> Fixing the answers for Question 28 AWS Marketplace does offer selling your / 3rd party software solutions

Wrong, AWS Marketplace primarily provides software solutions that are designed to run on AWS, not necessarily on other cloud vendors.

**Comment by kananinirav** [comment]
https://github.com/kananinirav/AWS-Certified-Cloud-Practitioner-Notes/commit/dbfc6f748c372d35ab319d832ae74ac96c4b267f

**Pull request closed without merging**
